### ISSUE TITLE
Coordination between the CG and WG

### ISSUE THREAD

**Issue by anssiko** [w3c/machine-learning-charter#10]
Nota bene: _The aspects discussed in this issue are operational, and as such we do not need to codify these aspects in the proposed charter document itself. That said, I thought it'd be good to share this proposal here to capture any comments and in general to give a heads-up to the community on what we're planning._

Given PR #9 suggests a close coordination between the Community Group and Working Group is needed, I propose the WG adopts [a work mode similar to the WebGPU CG and WG](https://lists.w3.org/Archives/Public/public-gpu/2020Aug/0003.html) to minimize the friction for participants while crossing the group boundary.

In practice this proposal, if adopted, would mean the CG/WG boundaries can remain pretty transparent for regular participants and the existing already familiar day-to-day tooling used in the CG would be shared with the WG. For example, both the CG and WG would use the same:

- Mailing list(s)
- GitHub org and repos
- Teleconferences and meetings

We'd automate tasks such as IPR checks on pull requests targeted at Working Group deliverables to make sure the participants can focus on the technical work without the need to worry about (less exciting) process-related aspects.

@tidoust, you set up the WebGPU CG/WG in this fashion couple of months ago. Feel free to share your experiences on how that has worked and what we should learn from you.

FYI @dontcallmedom

**Comment by dontcallmedom** [comment]
This looks good overall - my only suggestion is that it may not be needed to have shared repos between CG and WG which make it harder to track IPR contributions (at least in the current state of our tooling) and doesn't seem necessary in our case given that the WG charter would seem to leave enough room for it to work on e.g. new operations that wouldn't be a fit for the first release of WebNN.

In that sense, it would probably be closer to how the [Immersive Web CG/WG operates](https://immersive-web.github.io/) where a repo belongs to either the CG (for new specs in incubation) or the WG (for specs it has started pushing on the Rec track).

**Comment by anssiko** [comment]
IIUC, in this envisioned work mode we'd transition the ownership of the [webnn](https://github.com/webmachinelearning/webnn/ ) repo to the WG and work on any new operations for that API in scope of the WG.

I believe we could share the same GH organization between the CG and WG and let the repo be the boundary to make it easier to track IPR contributions.

The proposed Tentative Deliverables #9 would start their journey in CG-owned repos, either in [proposals](https://github.com/webmachinelearning/proposals) or in dedicated repos such as [model-loader](https://github.com/webmachinelearning/model-loader) and with good progress the repo ownership would be migrated to the WG.

@dontcallmedom does that sounds right?

(Linking to infra issue https://github.com/w3c/ash-nazg/issues/181 so we don't forget.)

**Comment by dontcallmedom** [comment]
that's exactly right @anssiko

**Comment by anssiko** [comment]
@dontcallmedom if you think we should tweak the charter language to accommodate this proposal, feel free to craft a PR for that. Otherwise, we feel free to close this issue.

**Comment by dontcallmedom** [comment]
let's close it - there is ongoing discussion adopting [pre-defined language](https://github.com/w3c/charter-drafts/issues/262) in charters to describe this type of relationships; I'll provide a pull request if and when it gets settled before we move forward with the review.
