### ISSUE TITLE
WebRTC coordination

### ISSUE THREAD

**Issue by anssiko** [w3c/machine-learning-charter#21]
(Related to the WebML WG Charter in development at https://github.com/w3c/machine-learning-charter/pull/19)

We added an [Integration with real-time video processing](https://www.w3.org/TR/webnn/#usecase-real-time-video-processing) use case based on learnings from our experimentation in https://github.com/webmachinelearning/webnn/issues/226

For the next charter, we could be more explicit and confident in [Coordination](https://www.w3.org/2021/04/web-machine-learning-charter.html#coordination), currently reads:

>[WebRTC Working Group](https://www.w3.org/groups/wg/webrtc)
>The WebRTC Working Group defines the MediaStream interface and related media processing APIs that likely make use of Machine Learning capabilities afforded by the WebNN API.

We could tweak this a little:

>[WebRTC Working Group](https://www.w3.org/groups/wg/webrtc)
>The WebRTC Working Group defines the MediaStream interface and related media processing APIs that enable integration with Machine Learning capabilities afforded by the WebNN API.

Or keep this intact. Thoughts @dontcallmedom?

**Comment by dontcallmedom** [comment]
I like the tweak, +1
