### ISSUE TITLE
Descriptive input formats for building graphs?

### ISSUE THREAD

**Issue by zolkis** [w3c/machine-learning-charter#26]
I wonder if the WG has discussed and rejected defining descriptive input (e.g. JSON, JSON-LD) for building graphs.

Currently compute graphs are built programmatically, but using dictionary options.
Taking that a bit further, an alternative could be adding generic ops (ops as string enum parameters) with input and output descriptions, options etc, that are specified in a dictionary (and serialized as JSON/-LD) and fed to a builder method.

That would allow e.g. prior transformations based on client needs. The code would look similar, just more dictionaries and less method calls.

**Comment by anssiko** [comment]
This proposal is a good candidate for https://github.com/webmachinelearning/proposals

@zolkis please feel free to [add a new proposal](https://github.com/webmachinelearning/proposals/issues/new?template=new-proposal.md) there. The path is: proposals -> CG -> WG.

**Comment by zolkis** [comment]
Closing for now.
