### ISSUE TITLE
OpenXLA coordination

### ISSUE THREAD

**Issue by anssiko** [w3c/machine-learning-charter#28]
We explored areas of collaboration with the OpenXLA project during our [WebML WG Teleconference – 17 November 2022](https://www.w3.org/2022/11/17-webmachinelearning-minutes.html).

We have done a small-scale [WebNN op compatibility exploration](https://github.com/webmachinelearning/webnn/blob/main/op_compatibility/first_wave_models.md) with XLA-HLO in 2020. During our call today there was an agreement we should consider revising this study with StableHLO that targets feature completeness EOY 2022. A good start for this effort would thus be ~Q1-Q2'23.

In terms of charter edits, this could be an addition to the [External Coordination](https://www.w3.org/2021/04/web-machine-learning-charter.html#external-coordination) section, for example:

>*[OpenXLA Project](https://github.com/openxla)*
>
> OpenXLA Project develops StableHLO, a portable ML compute operation set that makes frameworks easier to deploy across different hardware. WebNN API targets diverse hardware platforms and defines an operation set whose high-level operations can be decomposed to low level primitives that can map to StableHLO operations. Coordination and alignment between these two operation sets is beneficial to the open ML ecosystem.

**Comment by anssiko** [comment]
@burmako, we're proposing to add the OpenXLA Project into the Coordination section of the W3C Web Machine Learning Working Group Charter 2023-2025 as outlined in this issue. The proposed concrete changes are in the commits referenced in this issue. 

Please let us know what you think and whether you have any suggested changes. We're looking to submit the charter for W3C-wide review in ~Feb '23 so any proposals that arrive before that will be considered.

**Comment by theadactyl** [comment]
@anssiko we're happy to be included in the Coordination section, thank you!

**Comment by theadactyl** [comment]
@james-rubin could you take a look at the proposed wording here?

**Comment by anssiko** [comment]
@theadactyl thanks for the confirmation! Please let us know by early Feb '23 if you have changes in mind you'd like to propose. Or if you have any questions. The W3C's WebML WG looks forward to working with the OpenXLA Project.

As for the expectations regarding this concrete wording: the coordination statements are rather high level to allow for helpful interactions to happen between efforts. This may include cross-pollinating ideas, seeking drive-by reviews when proposals emerge that may intersect in meaningful ways etc. This does not ask for any additional formal structure and we do not want to create more meetings but can piggypack on existing ones when it makes sense. To make substantive contributions to either direction, folks are expected to adhere to the governance model of the project in question.
