### ISSUE TITLE
Detailed explainer for Web NN API

### ISSUE THREAD

**Issue by jbingham** [w3c/machine-learning-charter#3]
We at Google are concerned there is insufficient detail in this incubation to proceed to a standard.  Could the CG have a conversation about the potential for creating a Working Group prior to drafting this charter? For example, it would be great to see a detailed Explainer fleshed out first.

Let’s clarify what the rationale is for this approach, as opposed to others, and why some feel it’s ready to move to the standard track.

**Comment by anssiko** [comment]
@jbingham, thanks for bumping the priority of this exercise.

The WebNN API editors @wchao1115 @huningxin would appreciate more specific questions (similarly to #2) the explainer doc should provide answers to. That way the doc can cater to its audience the best. 

@jbingham, could you take the lead on soliciting the questions?

I’ll drop some references below.

WIP explainer:

https://github.com/webmachinelearning/webnn/blob/master/explainer.md

Related tracking issues:

https://github.com/webmachinelearning/webnn/issues/18
https://github.com/webmachinelearning/webnn/issues/89
https://github.com/webmachinelearning/webnn/issues/74

The explainer has been discussed on CG calls, most recently 01 Oct 2020 with actions taken to improve the explainer:

https://github.com/webmachinelearning/meetings/search?q=%22webnn%2Fblob%2Fmaster%2Fexplainer.md%22&type=

The next opportunity for discussing the proposed Working Group is the WebML CG Virtual Meeting at TPAC 2020 – 22 October 2020 - 14:00-15:00 UTC+0:

https://github.com/webmachinelearning/meetings/tree/master/2020-10-22-tpac2020

**Comment by anssiko** [comment]
@jbingham, the explainer has been fleshed out based on your feedback: https://github.com/webmachinelearning/webnn/blob/master/explainer.md

Please take a look and document any open questions here so the document can be further improved. Your feedback is much appreciated!

**Comment by jbingham** [comment]
Thanks for the updates,  @anssiko . This is much improved. Let's close out this issue, and we can discuss any questions in new issues.

**Comment by anssiko** [comment]
Thanks @jbingham for filing the specific issues. Please join us to discuss your feedback this Thu:

https://github.com/webmachinelearning/meetings/blob/master/telcons/2020-11-12-agenda.md
