### ISSUE TITLE
AC review comments

### ISSUE THREAD

**Issue by chrisn** [w3c/machine-learning-charter#32]
I have a few comments and questions following my AC review of the [Web ML charter](https://w3c.github.io/machine-learning-charter/charter.html):

1. In section 2, the "Allows to ..." phrasing seems strange. Suggest "Allows construction of ...", "Allows compilation of ...", ""Allows input to be set up ..."
2. In section 2, should "are not be tied" be "are not tied" or "are not to be tied"? And similar for "are to be implementable"
3. In section 2, "It may also work on", it's not clear what "It" refers to. I suggest "The Working Group may also work on"
4. In section 3.2, the Model Loader API state is "Adopted from the Web ML CG". Has this document now been adopted into the WG? If it has, what further progress is expected from the CG (the charter says "Depending on the CG progress")? If it hasn't, should the status be "Draft CG Report" rather than "Adopted from the Web ML CG"?
5. In section 5.2, "how WebNN access data" should be "how WebNN accesses data"
6. In section 6, "(Working|Interest)" should be "Working"
7. In section 12, the change log is empty. Should this section describe changes from the previous charter?

**Comment by dontcallmedom** [comment]
thanks @chrisn - I've submitted https://github.com/w3c/machine-learning-charter/pull/33 which I hope addresses most of your comments.

on (2), I'm not sure I understand what you're suggesting to change in "are to be implementable"

on (7), I understand the changelog section is only expected to document changes to the charter *after* it has been approved by the Director (see https://github.com/w3c/charter-drafts/commit/9921aa2d77a6fd8af794aed380b78ae0a934f97e); changes from the previous charter are expected to be documented in the charter history section (which I believe I would fill after the AC review, before it gets announced to the AC)

**Comment by chrisn** [comment]
Thank you! For (2), it's the difference between stating as a requirement:

* "The APIs in scope of this group **are not to be tied** to any particular platform and **are to be implementable** on top of existing major platform APIs ..."

and phrasing as a fact:

* "The APIs in scope of this group **are not tied** to any particular platform and **are implementable** on top of existing major platform APIs ..."

and I wasn't sure which one was intended.

For (7), that's helpful to know, thank you.

**Comment by anssiko** [comment]
In the current charter text (authored in 2021) this was worded in a future tense form:

>The APIs in scope of this group will not be tied to any particular platform and will be implementable on top of existing major platform APIs

The "as a fact" proposal sounds more natural to a non-native speaker. If there's an established convention for charter language (similarly to spec prose) aligning with it would be preferred.

**Comment by dontcallmedom** [comment]
I've updated #33 accordingly - @chrisn can you check that it does indeed address completely your review at this stage?

**Comment by chrisn** [comment]
> I've updated #33 accordingly - @chrisn can you check that it does indeed address completely your review at this stage?

Thank you. It does, yes.
