### ISSUE TITLE
Possible data process spec

### ISSUE THREAD

**Issue by WenheLI** [w3c/machine-learning-charter#4]
In our practice of porting Machine Learning/Deep Learning eco-system to JavaScript, we found that, despite the well-discussed machine learning use cases, runtime, efficiency, and privacy concern, the data and data process pipeline/spec should also be discussed.

The needs are mainly addressed by the fact that the deep learning models can not work independently and data process is needed for both the inputs and outputs of one model. 

Therefore, we are thinking if it is possible to set up such a data process spec that offers a universal & handy-dandy API set for data related operation.

**Comment by anssiko** [comment]
Thanks @WenheLI for the proposal! This repo (https://github.com/w3c/machine-learning-charter/) is for discussing the proposed Web Machine Learning Working Group Charter that has in scope the Web Neural Network API that has been incubated for a couple of years now.

We've created a separate repo https://github.com/webmachinelearning/proposals to discuss new specification proposals that have not yet been incubated, and your proposal for a data process spec would be a good (first!) candidate to be submitted to that repository. Please follow the hopefully simple [instructions](https://github.com/webmachinelearning/proposals/blob/master/README.md).

I'll close this issue so the discussion on your proposal can continue in the right place after you've opened the issue there. Thanks!
