### ISSUE TITLE
Evidence of customer demand that’s not met by WebGL and WASM

### ISSUE THREAD

**Issue by jbingham** [w3c/machine-learning-charter#5]
In order to support adding new web ML APIs to Chromium, it would be helpful to have examples of customers who would in fact use this functionality if it shipped. 

An ideal customer would meet these criteria:
* Has already deployed ML models into web apps using existing JavaScript libraries
* Has tried WebGL or WASM in earnest (or WebGL/WASM-based libraries like TensorFlow.js) and has performance data indicating that it will not work for their needs
* Is willing to meet and talk about their requirements.

We already believe that web ML APIs will be beneficial for performance, and we are convinced of the theoretical benefit. In this thread, let’s capture customers willing to go on the record about their experiences with ML on the web today.

**Comment by anssiko** [comment]
Per discussion on the [WebML CG Teleconference – 10 December 2020](https://www.w3.org/2020/12/10-webmachinelearning-minutes.html) this issue can be closed.
