### ISSUE TITLE
Graph vs model loader

### ISSUE THREAD

**Issue by jbingham** [w3c/machine-learning-charter#6]
If the Community Group could agree on a model format, would we prefer to ship a model loader API instead?

**Comment by anssiko** [comment]
I believe the proposed PR #9 would address this issue too.

The following text from the PR would imply in this case if the Community Group agrees on a model format and the API proposal overall is considered sufficiently incubated, the Model Loader API could advance into a WG normative specification:

>Depending on the Community Group progress, this Working Group may deliver the following W3C normative specifications after sufficient incubation in the Community Group

@jbingham does that sounds correct?

**Comment by jbingham** [comment]
Expanding the charter should unblock us from forming a Working Group, yes. 

That still leaves the question unanswered. We should have an issue to address that question. Should it be filed against the charter, or where?

**Comment by anssiko** [comment]
New proposals for the WebML CG such as the model format should be filed at: https://github.com/webmachinelearning/proposals

Other CGs have similar proposals repos:
https://github.com/WICG/proposals
https://github.com/immersive-web/proposals

You can check them out for inspiration.

**Comment by jbingham** [comment]
That's a slightly different question from what was asked in this Issue.
This issue is about the approach proposed in the Charter, and is not a new
proposal.

Given that, would it make sense to discuss it here first?

**Comment by anssiko** [comment]
Yes, discussion is welcome in this charter repo.

(I pointed to the proposals repo as the place to flesh out a concrete proposal. For the CG to agree to start new work, it is a best practice to have a concrete proposal in that repo.)

**Comment by jbingham** [comment]
Let me try to ask the question in a different way:

What is the use case where a web developer would want to dynamically construct a graph at runtime, rather than load a predefined graph?

If the typical use case is that the model graph is fully defined in advance, web developers have a choice:
1) They can import a javascript library that loads a model format at runtime, parses it, and constructs the graph in javascript using the Web NN API. Then compile and predict with it.
2) They can run an offline script that converts their model format to javascript, using the Web NN API. Then at runtime, they can load the javascript model format, then compile and predict with it.

Either way, the end result is the same.  1) adds some bytes and runtime costs, likely not that large compared to the cost of doing ML. 2) treats the Web NN API as basically a model format that happens to be in javascript rather than a protocol buffer or flat buffer. 

Is there any other reason to prefer 1)?

**Comment by anssiko** [comment]
Per discussion on the [WebML CG Teleconference – 10 December 2020](https://www.w3.org/2020/12/10-webmachinelearning-minutes.html) this issue can be closed.
